### ISSUE TITLE
GreaterThan/LessThan operators are not valid for System.Guid

### ISSUE THREAD

**Issue by ashf** [mrahhal/MR.EntityFrameworkCore.KeysetPagination#1]
Like strings, Guids also need to use compareto for boolean operators.

**Comment by mrahhal** [comment]
Releasing the fix. Will post here what package version to use after it's released.

**Comment by mrahhal** [comment]
Pushed [v0.1.3](https://www.nuget.org/packages/MR.EntityFrameworkCore.KeysetPagination/0.1.3). Let me know if it works for you. Thanks!

**Comment by ashf** [comment]
Tested and working. Thanks!
