### ISSUE TITLE
Nested types

### ISSUE THREAD

**Issue by hey-red** [mrahhal/MR.EntityFrameworkCore.KeysetPagination#15]
Is there a way to use nested types in builder?

For example:

`context.SomeModel.KeysetPaginate(b => b.Descending(entity => entity.Options.SomeOption), reference: new { Options = new { SomeOption = value } });`

**Comment by mrahhal** [comment]
Right now this isn't possible. But I think it might work as long as you make sure the nested prop is loaded in the reference, but a part of the implementation does need to change. I'll try and have a look if this is doable.

**Comment by MrNickGreene** [comment]
I would also find this helpful.

**Comment by mrahhal** [comment]
Initial support for this added in [v1.1.0](https://www.nuget.org/packages/MR.EntityFrameworkCore.KeysetPagination/1.1.0). Let me know if it works for your use cases. Make sure to check the new section in the README about it.

If you're using this package transitively through MR.AspNetCore.Pagination, you of course can add a dependency to this version directly to get this support.
