### ISSUE TITLE
GreaterThan/LessThan operators are not valid for System.Bool

### ISSUE THREAD

**Issue by Denvek** [mrahhal/MR.EntityFrameworkCore.KeysetPagination#16]
You currently can't page when ordering by boolean fields because the LINQ comparison operators aren't valid for System.Bool. It looks like this is similar to issue #1 just for a different type.

**Comment by mrahhal** [comment]
Yes, should be an easy fix. If no one else volunteers I'll get to it soon.

**Comment by mrahhal** [comment]
[v1.0.2](https://www.nuget.org/packages/MR.EntityFrameworkCore.KeysetPagination/1.0.2)
