### ISSUE TITLE
Parametrized queries

### ISSUE THREAD

**Issue by raffaele-cappelli** [mrahhal/MR.EntityFrameworkCore.KeysetPagination#17]
Just a comment: using "var referenceValueExpression = Expression.Constant(referenceValues[j]);" the resulting SQL will contain literal values, while it should be more efficient using parameters (the DBMS should be able to reuse the plan). Have you tried to generate expressions that will be translated into parametrized SQL? 
See for instance: https://stackoverflow.com/questions/71019162/how-to-force-sql-parameter-instead-of-constant-in-expression-predicate

**Comment by mrahhal** [comment]
That's interesting, didn't know about it. Will have a look at this later. Thanks!

**Comment by mrahhal** [comment]
[v1.0.3](https://www.nuget.org/packages/MR.EntityFrameworkCore.KeysetPagination/1.0.3)
