### ISSUE TITLE
Extend builder to pass member access by dot '.' notation string

### ISSUE THREAD

**Issue by CaminGui** [mrahhal/MR.EntityFrameworkCore.KeysetPagination#31]
As a developer I want to be able to specify member to acces using string dot '.' notation.

Our frontend just send to us the member path to order on in dot notation form.

This also ease the way we access Json fields in our backend.

```cs
public class NestedJsonModel
{
    public int Id { get; set; }
    public NestedInnerJsonModel Inner { get; set; }
}

public class NestedInnerJsonModel
{
    public int Id { get; set; }
    public DateTime Created { get; set; }
    public JsonDocument Data { get; set; }
}

var context = query..KeysetPaginateQuery(
			b => b.Ascending("inner.data.nbString"),
			KeysetPaginationDirection.Forward);
``` 

For Json property we also need an extra parameter to convert the JsonElement to the value type.

It can also be use in other cases for type convertion.

```cs
MethodInfo converter = typeof(JsonElement).GetMethod(....);
var context = query..KeysetPaginateQuery(
			b => b.Ascending("inner.data.nbString", converter),
			KeysetPaginationDirection.Forward);
```

**Comment by mrahhal** [comment]
I'm hesitant about this as well. Not having proper indexing completely defeats the point of doing keyset pagination. Your code snippet above is saying you can create a keyset out of anything and everything, which doesn't really make sense.

If you have well known cases (which you can index properly), then I recommend your frontend send some kind of enum (or whatever you like) that identifies which case you want, and then switch on that and build your keyset. Having this dynamic string support will encourage creating keysets out of anything, which is something I don't want.
