### ISSUE TITLE
Is this package not maintained any more

### ISSUE THREAD

**Issue by tnlthanzeel** [mrahhal/MR.EntityFrameworkCore.KeysetPagination#34]
Is this package not maintained any more?

**Comment by mrahhal** [comment]
Why would it be not maintained anymore? It's stable.

**Comment by tnlthanzeel** [comment]
Oh okay, i was having ideas after i watched the community standup meeting on pagination with ef core and shay suggested some changes to get reduce the number of round trips. Okay cool thanks

**Comment by mrahhal** [comment]
If you're doing some work on some idea would be better to open an issue for discussing that first so that I can validate if it's something I would take.
