### ISSUE TITLE
Performing subtraction in a query breaks sorting

### ISSUE THREAD

**Issue by atrauzzi** [mrahhal/MR.EntityFrameworkCore.KeysetPagination#35]
We're using subtraction of dates or `EF.Functions.DateDiffHour()` in a query we're trying to keyset paginate.

Unfortunately, this is resulting in a LINQ error that the query can no longer be compiled.

Is there a limitation that would prevent sorting on computed columns?

**Comment by mrahhal** [comment]
Can you show the actual error with the stacktrace alongside the pagination code? It seems this is coming from EF itself so I'm wondering where KeysetPagination's involvement is here.

And to answer the question, no there's no limitation. There are already [examples](https://github.com/mrahhal/MR.EntityFrameworkCore.KeysetPagination/blob/main/samples/Basic/Pages/Computed.cshtml.cs) and [tests](https://github.com/mrahhal/MR.EntityFrameworkCore.KeysetPagination/blob/9336a8ee0a3ddb5da03347521411fb7ed6516304/test/MR.EntityFrameworkCore.KeysetPagination.Tests/KeysetPaginationTest.cs#L364) showing pagination over computed columns.

**Comment by mrahhal** [comment]
I'm closing this, please reopen with more details if you still have issues.
