### ISSUE TITLE
HasNextAsync returns false when it should be true for nullable column

### ISSUE THREAD

**Issue by Konopnik** [mrahhal/MR.EntityFrameworkCore.KeysetPagination#56]
When there is desc order by nullable column + asc by id and it is called with reference with null value in nullable column HasNextAsync will return always false.

Here you have test which will fail:
```	
[Fact]
	public async Task HasNext_WithDescendingNullableColumnWhereTheValueIsNull_ShouldBeTrue()
	{
		// The last page.
		var keysetContext = DbContext.MainModels.Where(x=>x.CreatedNullable == null).KeysetPaginate(
			b => b.Descending(x => x.CreatedNullable).Ascending(x => x.Id),
			KeysetPaginationDirection.Forward);
		var data = await keysetContext.Query
			.Take(1)
			.ToListAsync();
		keysetContext.EnsureCorrectOrder(data);

		// Next on the first item => should be true
		var hasNext = await keysetContext.HasNextAsync(data);

		hasNext.Should().BeTrue();
	}
```

**Comment by mrahhal** [comment]
Thanks for providing a test. Having a nullable column in the keyset is not supported as mentioned in [caveats.md](https://github.com/mrahhal/MR.EntityFrameworkCore.KeysetPagination/blob/main/docs/caveats.md#null). The same link also includes more info about the reason and potential solutions. This library also ships with an analyzer that would have flagged nullable keysets as warnings, as it's impossible to reliably deal with DB nulls in a keyset.

**Comment by mrahhal** [comment]
I'm closing this, please reopen if you still have issues.
